server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
      consul:
        enabled: true
      discovery:
        query-passing: true
    gateway:
      routes:
        - id: multiplication
          uri: lb://multiplication
          predicates:
            - Path=/challenges/**,/attempts,/attempts/**,/accounts/**
        - id: gamification
          uri: lb://gamification
          predicates:
            - Path=/leaderboard
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: http://localhost:3000
            allowed-headers: "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "OPTIONS"
      default-filters:
        - name: Retry
          args:
            retries: 3
            methods: GET,POST
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
logging:
  level:
    org.springframework.cloud.gateway.handler.predicate: trace
